import Foundation

/// Localized string keys used across the app foundation.
enum AppStrings {
    static let dashboardTitle = LocalizedStringResource("dashboard.title")
    static let dashboardPlaceholderMessage = LocalizedStringResource("dashboard.placeholder.message")
    static let dashboardEmptyMessage = LocalizedStringResource("dashboard.empty.message")
    static let dashboardAddMeterButton = LocalizedStringResource("dashboard.addMeter.button")
    static let dashboardEditButton = LocalizedStringResource("dashboard.edit.button")
    static let dashboardDoneButton = LocalizedStringResource("dashboard.done.button")
    static let dashboardShowToggle = LocalizedStringResource("dashboard.show.toggle")
    static let dashboardEditDashboardButton = LocalizedStringResource("dashboard.editDashboard.button")
    static let dashboardNoVisibleMetersMessage = LocalizedStringResource("dashboard.noVisibleMeters.message")
    static let dashboardNoReadingValue = LocalizedStringResource("dashboard.noReading.value")
    static let dashboardNoReadingDate = LocalizedStringResource("dashboard.noReading.date")
    static let dashboardLatestReadingFormat = LocalizedStringResource("dashboard.latestReading.format")
    static let dashboardSparklineAccessibilityLabel = LocalizedStringResource(
        "dashboard.sparkline.accessibility.label"
    )
    static let dashboardKpiMeterCount = LocalizedStringResource("dashboard.kpi.meterCount")
    static let dashboardKpiLatestReading = LocalizedStringResource("dashboard.kpi.latestReading")
    static let dashboardKpiMonthConsumption = LocalizedStringResource("dashboard.kpi.monthConsumption")
    static let dashboardKpiYearConsumption = LocalizedStringResource("dashboard.kpi.yearConsumption")
    static let dashboardKpiMonthCost = LocalizedStringResource("dashboard.kpi.monthCost")

    static let metersTitle = LocalizedStringResource("meters.title")
    static let metersPlaceholderMessage = LocalizedStringResource("meters.placeholder.message")
    static let metersEmptyMessage = LocalizedStringResource("meters.empty.message")
    static let metersAddButton = LocalizedStringResource("meters.add.button")
    static let metersDeleteAction = LocalizedStringResource("meters.delete.action")

    static let readingsTitle = LocalizedStringResource("readings.title")
    static let readingsPlaceholderMessage = LocalizedStringResource("readings.placeholder.message")
    static let readingsNoMetersMessage = LocalizedStringResource("readings.noMeters.message")
    static let readingsSelectMeterTitle = LocalizedStringResource("readings.selectMeter.title")
    static let readingsEmptyMessage = LocalizedStringResource("readings.empty.message")
    static let readingHistoryTitle = LocalizedStringResource("reading.history.title")
    static let readingAddButton = LocalizedStringResource("reading.add.button")
    static let readingCreateTitle = LocalizedStringResource("reading.create.title")
    static let readingEditTitle = LocalizedStringResource("reading.edit.title")
    static let readingDetailTitle = LocalizedStringResource("reading.detail.title")
    static let readingDateField = LocalizedStringResource("reading.date.field")
    static let readingValueField = LocalizedStringResource("reading.value.field")
    static let readingNoteField = LocalizedStringResource("reading.note.field")
    static let readingSaveButton = LocalizedStringResource("reading.save.button")

    static let analyticsTitle = LocalizedStringResource("analytics.title")
    static let analyticsPlaceholderMessage = LocalizedStringResource("analytics.placeholder.message")
    static let analyticsEmptyMessage = LocalizedStringResource("analytics.empty.message")
    static let analyticsPeriodPickerTitle = LocalizedStringResource("analytics.period.picker.title")
    static let analyticsPeriodWeek = LocalizedStringResource("analytics.period.week")
    static let analyticsPeriodMonth = LocalizedStringResource("analytics.period.month")
    static let analyticsPeriodYear = LocalizedStringResource("analytics.period.year")
    static let analyticsComparisonTitle = LocalizedStringResource("analytics.comparison.title")
    static let analyticsComparisonSubtitle = LocalizedStringResource("analytics.comparison.subtitle")
    static let analyticsConsumptionChartTitle = LocalizedStringResource("analytics.chart.consumption.title")
    static let analyticsCostChartTitle = LocalizedStringResource("analytics.chart.cost.title")
    static let analyticsMonthComparisonTitle = LocalizedStringResource("analytics.chart.monthComparison.title")
    static let analyticsYearComparisonTitle = LocalizedStringResource("analytics.chart.yearComparison.title")
    static let analyticsChartDateAxis = LocalizedStringResource("analytics.chart.axis.date")
    static let analyticsChartValueAxis = LocalizedStringResource("analytics.chart.axis.value")
    static let analyticsChartCostAxis = LocalizedStringResource("analytics.chart.axis.cost")

    static let settingsTitle = LocalizedStringResource("settings.title")
    static let settingsPlaceholderMessage = LocalizedStringResource("settings.placeholder.message")

    static let createMeterTitle = LocalizedStringResource("meter.create.title")
    static let editMeterTitle = LocalizedStringResource("meter.edit.title")
    static let meterDetailTitle = LocalizedStringResource("meter.detail.title")
    static let meterNameField = LocalizedStringResource("meter.name.field")
    static let meterTypeField = LocalizedStringResource("meter.type.field")
    static let meterCustomTypeField = LocalizedStringResource("meter.customType.field")
    static let meterUnitField = LocalizedStringResource("meter.unit.field")
    static let meterSerialNumberField = LocalizedStringResource("meter.serialNumber.field")
    static let meterSaveButton = LocalizedStringResource("meter.save.button")
    static let meterCreateButton = LocalizedStringResource("meter.create.button")
    static let meterEditButton = LocalizedStringResource("meter.edit.button")
    static let meterCancelButton = LocalizedStringResource("meter.cancel.button")
    static let meterNotProvided = LocalizedStringResource("meter.notProvided")
    static let meterFormSectionDetails = LocalizedStringResource("meter.form.section.details")
    static let meterDetailSection = LocalizedStringResource("meter.detail.section")
    static let meterTypeElectricityImport = LocalizedStringResource("meter.type.electricityImport")
    static let meterTypePVFeedIn = LocalizedStringResource("meter.type.pvFeedIn")
    static let meterTypeGas = LocalizedStringResource("meter.type.gas")
    static let meterTypeWater = LocalizedStringResource("meter.type.water")
    static let meterTypeDistrictHeating = LocalizedStringResource("meter.type.districtHeating")
    static let meterTypeHeatingOil = LocalizedStringResource("meter.type.heatingOil")
    static let meterTypeCustom = LocalizedStringResource("meter.type.custom")

    static let validationMeterNameRequired = LocalizedStringResource("validation.meter.name.required")
    static let validationMeterNameTooLong = LocalizedStringResource("validation.meter.name.tooLong")
    static let validationMeterUnitRequired = LocalizedStringResource("validation.meter.unit.required")
    static let validationMeterUnitTooLong = LocalizedStringResource("validation.meter.unit.tooLong")
    static let validationReadingValueRequired = LocalizedStringResource("validation.reading.value.required")
    static let validationReadingValueNumeric = LocalizedStringResource("validation.reading.value.numeric")
    static let validationReadingValueNonNegative = LocalizedStringResource("validation.reading.value.nonNegative")
    static let validationReadingValueBelowLatest = LocalizedStringResource("validation.reading.value.belowLatest")
    static let validationReadingLargeJump = LocalizedStringResource("validation.reading.largeJump")
    static let errorGeneric = LocalizedStringResource("error.generic")
}
